# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpiritPets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpiritPets
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'SpiritPetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpiritPetsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SpiritPets WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpiritPets WatchKit App

end

target 'SpiritPets WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpiritPets WatchKit Extension

end
